[package]
name = "nero-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
wasm-metadata = "0.227.1"
wasmtime = { workspace = true }
