[package]
name = "nero-app"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", default-features = false, features = [
    "config-toml",
] }

[dependencies]
anyhow = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
tauri = { version = "2", features = ["config-toml"] }
tracing = { workspace = true }
tracing-subscriber = "0.3.20"
url = { workspace = true }
nero-processors = { path = "../processors" }
nero-extensions = { path = "../extensions" }
nero-wasm-host = { path = "../wasm-host" }

[features]
custom-protocol = ["tauri/custom-protocol"]
